micronaut:
  application:
    name: dynquery
  server:
    port: 8090
jackson:
  serialization:
    writeDatesAsTimestamps: false
    failOnUnknownProperties: true
datasources:
  default:
    url: jdbc:h2:mem:devDb;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE
    driverClassName: org.h2.Driver
    username: sa
    password: ''
    dialect: H2
jpa:
  default:
    properties:
      hibernate:
        hbm2ddl:
          auto: create
        show_sql: true
    entity-scan:
      packages:
        - 'com.snourian.example.dynquery.domain'
      classpath: false
    compile-time-hibernate-proxies: true